# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Liam Galvin
email: liamgalvin@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal dumping ground of an engineer, hacker, and general code mangler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.liam-galvin.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: liam_galvin
github_username:  liamg

# Build settings
remote_theme: liamg/jekyll-theme-console

plugins:
  - jekyll-remote-theme
  - jekyll-feed

header_pages:
  - index.md
  - about.md

style: light # dark (default), light or hacker
listen_for_clients_preferred_style: false

footer: 'follow me on <a target="_blank" noopener href="https://github.com/liamg">github</a> / <a target="_blank" noopener href="https://twitter.com/liam_galvin">twitter</a>'

google_analytics: UA-10622185-1

exclude:
  - .idea/*
  - Makefile
  - scripts/*
  - README.md
